# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy DevLens

on:
  push:
    branches:
      - development
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build DevLens/DevLens.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish DevLens/DevLens.csproj -c Release --property:PublishDir=${{env.DOTNET_ROOT}}/myapp
     
      # - name: Create ZIP package
      #   run: |
      #     cd ${{ env.DOTNET_ROOT }}
      #     zip -r myapp.zip myapp/
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          # path: ${{env.DOTNET_ROOT}}/myapp.zip
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'test'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Azure Login
        uses: Azure/login@v2.2.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
          
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
              
      # - name: Stop Azure App Service
      #   run: |
      #      az webapp stop --name ${{ secrets.AZURE_WEBAPP_NAME }} \
      #                     --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
      #                     --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                       
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3.0.1
        with:
          app-name: 'devlens'
          # package: './myapp.zip'
          package: '.'
          clean: true
          restart: true
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
      
      # - name: Start Azure App Service
      #   run: |
      #     az webapp start --name ${{ secrets.AZURE_WEBAPP_NAME }} \
      #                     --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
      #                     --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
