# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
name: Build and deploy DevLens Test

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      ASPNETCORE_ENVIRONMENT: "Test"
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build DevLens/DevLens.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish DevLens/DevLens.csproj -c Release --property:EnvironmentName="Test" --property:PublishDir="${{env.DOTNET_ROOT}}/myapp"

      - name: Copy Markdown file to publish directory
        run: |
          cp README.md "${{env.DOTNET_ROOT}}/myapp/README.md"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: "${{env.DOTNET_ROOT}}/myapp"

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Test'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6712230EBC0546178D2228D3FFC99C1C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_156D2EF9FF5249FCA63842BEDEAED19B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CDEEE8F8F3A74A8A9E1D8895538631B2 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'devlens-test'
          slot-name: 'Production'
          package: .
          
